PMGR-9774
patronmanager/patronmanager-api-docs.github.io pull request #4
Opened 2021-04-01 17:40 UTC by tfuda

Add descriptions for new properties on the EI (contentFormat and isPasscodeEligible). Also, update the API sample to match current reality.

2021-04-01 20:08 UTC, daveespo requested changes

2021-04-01 20:08 UTC, daveespo commented on public-event-list.md
> +      "detail" : null,
Let's add sample `detail` and `address` to show that it can contain HTML (can address contain HTML?)

2021-04-01 20:08 UTC, daveespo commented on public-event-list.md
> +    public Boolean soldOut = true; // False unless all TAs are sold out
These comments are actually in the Apex class and I usually just copy/paste the whole set of inner classes into this doc so can you also make sure these comments make their way back into the Apex file?

2021-04-01 20:08 UTC, daveespo commented on public-event-list.md
> +    "purchaseUrl" : "https://sandbox-littledipper-aries-5925-1786f2f1715.cs45.force.com/ticket/#/events/a178A000002gtOIQAY",
Let's change this URL to be the same fictional sillytickets.secure.force.com we had before so no one arrives trying to scrape your fake tickets

2021-04-01 20:08 UTC, daveespo commented on public-event-list.md
> +      "name" : "Access Code Event (PYOS) Dec. 25th 2029 8pm",
Let's get rid of these fake looking names; in the real world, it would just be the "Dec. 25th, 2029 8pm"

2021-04-01 20:08 UTC, daveespo commented on public-event-list.md
> +    "name" : "Test Event",
"Romeo and Juliet" or something instead of Test Event

2021-04-01 20:08 UTC, daveespo commented on public-event-list.md
> +    "smallImagePath" : null,
let's take out the `smallImagePath` and other fields that we're not documenting from the sample

2021-04-05 17:50 UTC, tfuda reviewed
> *[Reviewable](https://reviewable.io/reviews/patronmanager/patronmanager-api-docs.github.io/4)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @daveespo)

___
*[public-event-list.md, line 56 at r1](https://reviewable.io/reviews/patronmanager/patronmanager-api-docs.github.io/4#-MXIbxW-tXWwtqq2Pn5u-r1-56:-MXY92tlE-5qnGPCj0pk:b-896fix) ([raw file](https://github.com/patronmanager/patronmanager-api-docs.github.io/blob/623ad0eab93dcc165c97eccf7d5cd7a62687af71/public-event-list.md#L56)):*
<details><summary><i>Previously, daveespo (David Esposito) wrote…</i></summary><blockquote>

These comments are actually in the Apex class and I usually just copy/paste the whole set of inner classes into this doc so can you also make sure these comments make their way back into the Apex file?
</blockquote></details>

Done.
___
*[public-event-list.md, line 146 at r1](https://reviewable.io/reviews/patronmanager/patronmanager-api-docs.github.io/4#-MXIbxW-tXWwtqq2Pn5u-r1-146:-MXY93uaDX656I1u8sp_:b-896fix) ([raw file](https://github.com/patronmanager/patronmanager-api-docs.github.io/blob/623ad0eab93dcc165c97eccf7d5cd7a62687af71/public-event-list.md#L146)):*
<details><summary><i>Previously, daveespo (David Esposito) wrote…</i></summary><blockquote>

Let's add sample `detail` and `address` to show that it can contain HTML (can address contain HTML?)
</blockquote></details>

Done.
___
*[public-event-list.md, line 160 at r1](https://reviewable.io/reviews/patronmanager/patronmanager-api-docs.github.io/4#-MXIbxW-tXWwtqq2Pn5u-r1-160:-MXY95ax4Y2yEOS_VFrJ:b-896fix) ([raw file](https://github.com/patronmanager/patronmanager-api-docs.github.io/blob/623ad0eab93dcc165c97eccf7d5cd7a62687af71/public-event-list.md#L160)):*
<details><summary><i>Previously, daveespo (David Esposito) wrote…</i></summary><blockquote>

let's take out the `smallImagePath` and other fields that we're not documenting from the sample
</blockquote></details>

Done.
___
*[public-event-list.md, line 161 at r1](https://reviewable.io/reviews/patronmanager/patronmanager-api-docs.github.io/4#-MXIbxW-tXWwtqq2Pn5u-r1-161:-MXY96XQEpS916C6GREd:b-896fix) ([raw file](https://github.com/patronmanager/patronmanager-api-docs.github.io/blob/623ad0eab93dcc165c97eccf7d5cd7a62687af71/public-event-list.md#L161)):*
<details><summary><i>Previously, daveespo (David Esposito) wrote…</i></summary><blockquote>

Let's change this URL to be the same fictional sillytickets.secure.force.com we had before so no one arrives trying to scrape your fake tickets 
</blockquote></details>

Done.
___
*[public-event-list.md, line 162 at r1](https://reviewable.io/reviews/patronmanager/patronmanager-api-docs.github.io/4#-MXIbxW-tXWwtqq2Pn5u-r1-162:-MXY97bF9_lpuSaA-474:b-896fix) ([raw file](https://github.com/patronmanager/patronmanager-api-docs.github.io/blob/623ad0eab93dcc165c97eccf7d5cd7a62687af71/public-event-list.md#L162)):*
<details><summary><i>Previously, daveespo (David Esposito) wrote…</i></summary><blockquote>

"Romeo and Juliet" or something instead of Test Event
</blockquote></details>

Done.
___
*[public-event-list.md, line 171 at r1](https://reviewable.io/reviews/patronmanager/patronmanager-api-docs.github.io/4#-MXIbxW-tXWwtqq2Pn5u-r1-171:-MXY98JT8wbKJK5xTAKR:b-896fix) ([raw file](https://github.com/patronmanager/patronmanager-api-docs.github.io/blob/623ad0eab93dcc165c97eccf7d5cd7a62687af71/public-event-list.md#L171)):*
<details><summary><i>Previously, daveespo (David Esposito) wrote…</i></summary><blockquote>

Let's get rid of these fake looking names; in the real world, it would just be the "Dec. 25th, 2029 8pm"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-05 18:44 UTC, daveespo approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/patronmanager/patronmanager-api-docs.github.io/4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tfuda)



<!-- Sent from Reviewable.io -->

2021-04-05 18:53 UTC, merged